require("core.plugin_config.autopairs")
require("core.plugin_config.treesitter")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.completions")
